// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuF90vQCZtkBerFIDYezzRewqtjWpd-G8',
    appId: '1:506228420577:web:39e8346fe76aaaa7fdaca0',
    messagingSenderId: '506228420577',
    projectId: 'restaurantapp-685a9',
    authDomain: 'restaurantapp-685a9.firebaseapp.com',
    storageBucket: 'restaurantapp-685a9.appspot.com',
    measurementId: 'G-T94T0VYN0X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrmPbBgaV3yMLtgXfSJOANtkh9RudekTk',
    appId: '1:506228420577:android:3a0ec3df6e1018b6fdaca0',
    messagingSenderId: '506228420577',
    projectId: 'restaurantapp-685a9',
    storageBucket: 'restaurantapp-685a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKhxKiDR44GZ10TiTekbQqEahgOT9cKow',
    appId: '1:506228420577:ios:3ee2310eba20a80dfdaca0',
    messagingSenderId: '506228420577',
    projectId: 'restaurantapp-685a9',
    storageBucket: 'restaurantapp-685a9.appspot.com',
    iosClientId: '506228420577-b663f7diqp4ki0gao5mce4otspqjjcn4.apps.googleusercontent.com',
    iosBundleId: 'com.example.restroApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKhxKiDR44GZ10TiTekbQqEahgOT9cKow',
    appId: '1:506228420577:ios:3ee2310eba20a80dfdaca0',
    messagingSenderId: '506228420577',
    projectId: 'restaurantapp-685a9',
    storageBucket: 'restaurantapp-685a9.appspot.com',
    iosClientId: '506228420577-b663f7diqp4ki0gao5mce4otspqjjcn4.apps.googleusercontent.com',
    iosBundleId: 'com.example.restroApp',
  );
}
